### ISSUE TITLE
When the autocompletion fails I get this message:<t> is undefined

### ISSUE THREAD

**Issue by mambolevis** [company-mode/company-mode#760]
Hi,

Different users in different programming languages have experimented that after finishing typing a word that the auto completion fails to complete, the following message is shown: <t> is undefined.

https://github.com/jorgenschaefer/elpy/issues/1299#issuecomment-366011304

In my case that happened with the latest update of company from melpa.

Thanks

**Comment by dgutov** [comment]
It might be company's fault. There was a major change made when working with asynchronous backend, at least. But I'm not seeing this problem.

How do I reproduce this? Please provide step-by-step scenario, preferably one that doesn't require Elpy to be installed.

**Comment by mambolevis** [comment]
In my case, I experimented this behaviour in C++ using company and irony. Let me explain that in three steps:
1. Add a new include file. I need to type first one letter and wait until the completion starts
![image](https://user-images.githubusercontent.com/13024208/36319571-a1feedfe-1343-11e8-8d2b-99258b9b25e4.png)

2. It works until I type `inc`
![image](https://user-images.githubusercontent.com/13024208/36319684-f9b5ce96-1343-11e8-8cab-ac37bfd73884.png)

3. Autocomplete fails when I add the next letter
![image](https://user-images.githubusercontent.com/13024208/36319776-4d16987c-1344-11e8-85fc-a1b42303163a.png)

4. After 23 seconds the message is shown in the minibuffer
`<t> is undefined`

I also noticed that the completion doesn't work if I write two or three words at once, for example:
![image](https://user-images.githubusercontent.com/13024208/36320092-4fc4e988-1345-11e8-8c22-4d9c81889313.png)


There is also a detriment in the completion performance

Thanks

**Comment by dgutov** [comment]
Thanks! I don't see this problem exactly, but managed to reproduce something almost as weird, with most likely the same underlying cause.

I'll push the fix out in a few minutes, please re-test when you can.

**Comment by mambolevis** [comment]
It works. Thanks

**Comment by dgutov** [comment]
Sorry, that one wasn't great, so I pushed a different one now. Please give it a whirl too.

**Comment by minimalprocedure** [comment]
the problem seem to go away... :) Thanks.

**Comment by minimalprocedure** [comment]
ok, no... the problem persist. It's not as pervasive as before but is here.

**Comment by dgutov** [comment]
@minimalprocedure Are solid way to reproduce it? The scenario described in this issue now works fine for me.

What's your version of Emacs, by the way?

**Comment by minimalprocedure** [comment]
I'm on spacemacs 0.200.13 and emacs 26.0.91 (clang 6 build on ubuntu xenial), but stable emacs is the same. Maybe with 26.0.91 this behaviour is less severe.
Problem persist on javascript layer which start a ternjs server (company-tern), with disabled tern-mode seem going away.  I think it's a problem of slow communication or synchronism between company and external programs. It does not happen, or at least it does not happen to me, with folders of few files but when files are many and complex yes.
Perhaps there are too many programs that communicate more or less simultaneously with company (tern, eslint, yasnippet...) but this until a few days ago was not a problem or at least it was not so obvious.

Anyway, is not a great problem disabling tern for me, only annoying :) and perhaps the problem persist only in company-tern or tern-mode directly...

![schermata da 2018-02-17 12-18-04](https://user-images.githubusercontent.com/77815/36340420-c49e1e9a-13dc-11e8-9421-468f3e8e23cc.png)

**Comment by dgutov** [comment]
>  I think it's a problem of slow communication or synchronism between company and external programs

I kind of doubt it. The backend I'm testing it on is company-clang with caching disabled (to do that, add `(no-cache t)` as the last case in its definition. It's certainly slow and (formerly) very flicker-y.

I can try tern, but if you're saying that it only happens in large projects, reproducing might take a while.

A picture is nice, but a gif, or a video (or an asciinema recording) would be more helpful.

And most importantly, if you `M-x toggle-debug-on-error`, does it pop up a backtrace when this error happens?

**Comment by minimalprocedure** [comment]
@dgutov here a [video](http://minimalprocedure.pragmas.org/video/emacs-t_is_undef.ogv) 
No backtrace on debug, only <t> is undefined.
But the same if for c file [video](http://minimalprocedure.pragmas.org/video/emacs_c-t_is_undef.ogv)

**Comment by dgutov** [comment]
Thank you. But I still can't reproduce, sorry (using the Emacs 26 branch, or Emacs 27).

A scenario starting with `emacs -Q -L ~/.emacs.d/elpa/company-20180216.1749 -l company` would help.

**Comment by minimalprocedure** [comment]
@dgutov thanks, with only company (tern and company-tern) it's ok. Uhm... It must be some other package that interferes in some way. I will try to investigate. :)

**Comment by minimalprocedure** [comment]
@dgutov good morning...
Only for info, in spacemacs without spell-checking layer the problem seem going away. Maybe it's a conflict with flycheck.
Anyway, thanks for all.

Massimo

**Comment by minimalprocedure** [comment]
@dgutov oh! Yes! flyspell, right!

**Comment by ejmg** [comment]
Came back here to comment that `flyspell-mode` and `flyspell-prog-mode` definitely is what continues this in python mode for me, fwiw. 

**However**, the patch @dgutov pushed hits at the core of the problem. It was only after programming for sometime that I noticed there were still occasional "stutters" in completions/input that threw this error. Disabling `flyspell-prog-mode` eliminated the rest for me.

It is kind of funny that a bug like `sit-for` surfaced recently. It might just be time for me and others to update our emacs.

**Comment by dgutov** [comment]
@ejmg Interesting. So, what version of Emacs were you seeing this in?

**Comment by ejmg** [comment]
I am on Ubuntu Xenial, 16.04, and built it directly from GNU's FTP server somewhile back.

```bash
💀 ↛  emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by dgutov** [comment]
@ejmg That's concerning. Have you tried Emacs 25.2? I tested all the discussed scenarios in it.

The only other relevant bug report I have found is https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23980. But it's only fixed in master (will become Emacs 27).

**Comment by dgutov** [comment]
And another question.

`flyspell-prog-mode` is necessary to reproduce the problem, right? What if you turn `company-mode` off, does it still occur then? If yes, does it also occur with an older version of `company-mode` e.g. 0.9.4?

**Comment by dgutov** [comment]
Finally managed to reproduce it myself. To answer the above questions:

* The bug is there in both Emacs 25.2 and the to-be-released Emacs 26.
* But not in master.
* The previous version of `company` doesn't trigger it; so it's a combination of the new async support in `company` and `flyspell-prog-mode`. 😞

**Comment by dgutov** [comment]
That should hopefully do it.

**Comment by ejmg** [comment]
Need help testing it? Sorry I didn't see your earlier replies. Just let me know :smile:

**Comment by dgutov** [comment]
Sure!

**Comment by dgutov** [comment]
Thanks for checking.

**Comment by minimalprocedure** [comment]
@dgutov after some coding I've not found any anomalies. Perhaps you can close the issue.

Massimo

**Comment by dgutov** [comment]
It already closed, but thank you.

**Comment by vkazanov** [comment]
Just a comment: this issue is not resolved on latest company-mode and Emacs 26.1. I've been suffering from this thing for quite some time.

Surprisingly, as mentions in the referencing [issue](https://github.com/jorgenschaefer/elpy/issues/1396), setting auto-save-timeout to non-nil/non-zero value fixes it.

Go figure... :-)

**Comment by dgutov** [comment]
@vkazanov That's unfortunate. Any chance you can produce a how-to-reproduce without Elpy?

**Comment by vkazanov** [comment]
Well, I mostly use Python with Elpy so that's how I reproduce it easily. Recap: on latest Elpy with latest company-mode I get the dreaded  "<t> is undefined" whenever autocompletion kicks in. That is, unless auto-save-timeout is non-zero/non-nil.

I'll try to reproduce with indepenently from Elpy it on Monday.

**Comment by dgutov** [comment]
Speaking of Elpy, have you tried doing what Jorgen asked in [his last comment there](https://github.com/jorgenschaefer/elpy/issues/1396#issuecomment-403079640)?

**Comment by vkazanov** [comment]
@dgutov yes, just tried it. The debugger does not kick in, same <t> message. Hm. This really feels like there's some Emacs weirdness.

**Comment by vkazanov** [comment]
@dgutov I also tried to reproduce the issue with company-jedi, with elpy disabled. I didn't get any errors! So it's something about the way Elpy uses company. I don't understand how auto-save-timeout might be related

**Comment by dgutov** [comment]
Interesting. I'll try to look into it, but if Elpy is the only environment this reproduces in, it might eventually be up to Jorgen to investigate.

Speaking of alternative solutions for Python development, I hear Anaconda is decent. And [company-anaconda](https://github.com/proofit404/company-anaconda/) also uses the asynchronous convention.

**Comment by vkazanov** [comment]
Thanks! 

I'll take a look at anaconda-mode. AFAIK, for autocompletion both use the Jedi but Elpy also comes with company-mode included.

**Comment by dgutov** [comment]
@vkazanov Not sure what you mean by "included". All three solutions integrate with company-mode.

**Comment by dgutov** [comment]
@ejmg Thanks for the update. :-)

> I am skeptical this is an issue of emacs 26.1

> I think the issue has probably something to do with Elpy

I am fairly sure it's both. It's a bug in Emacs that's fairly difficult to trigger, but Elpy somehow manages it (probably in combination with Company).

**Comment by manphiz** [comment]
Just to report that this is still happening to me on Emacs 26.1 + latest stable eglot (1.4) + flyspell(-prog)-mode.  Disabling flyspell-mode fixes this.  Also I don't have Elpy installed.

**Comment by dgutov** [comment]
As mentioned in the other issue, the fix is in Emacs 26.2. You can wait for it to be released, or download and build a pretest version.

**Comment by manphiz** [comment]
@dgutov Thanks for the pointer! Guess I'll have to wait for 26.2 and disable flyspell in the meantime.
